import { FormEvent, MouseEventHandler, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Flex, Box, Text, Input, Button, Image, Tabs, TabList, TabPanels, Tab, TabPanel } from '@chakra-ui/react';
import { Openmeteo } from '../services/axios';



const Home: NextPage = () => {
  

  async function onSubmit(event: FormEvent){
  }
  let dados
   
  const consultaApi = (event: React.MouseEvent<HTMLButtonElement>) => {
    // dados = await Openmeteo.get(`latitude=${latitude}&longitude=${longitude}&hourly=temperature_2m,relativehumidity_2m&daily=temperature_2m_max,temperature_2m_min&timezone=Europe%2FLondon`)
    dados= "deucerto"
    event.preventDefault();

    const button: HTMLButtonElement = event.currentTarget;
    console.log(dados);
    console.log(button.name)
  };
  
  return (
    <Flex bgImage="ceu.jpg" bgRepeat="no-repeat" bgSize={"cover"}>
    
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <Flex  w='100vh' h='100vh' justify-content= 'center' bg="red.10" > 
                <Tabs  align='center' variant='soft-rounded' colorScheme='blue' >
                  <TabList>
                  <Tab>Londres</Tab>
                  <Tab>New York</Tab>
                  <Tab>Brasilia</Tab>
                  <Tab>Tokyo</Tab>
                  <Tab>Cairo</Tab>
                  <Tab>Camberra</Tab>
                </TabList>
                <TabPanels>
                {/* Londres */}
                <TabPanel > 
                  Openmeteo.get(latitude=51.5002&longitude=-0.1262&hourly=temperature_2m,relativehumidity_2m&daily=temperature_2m_max,temperature_2m_min&timezone=Europe%2FLondon)  
                </TabPanel>
                {/* New York */}
                <TabPanel> 
                  
                  <Button colorScheme='blue' name='2' onClick={consultaApi}>Nova Iorque</Button>
                </TabPanel>
                {/* Brasilia */}
                <TabPanel> 
                <Button colorScheme='blue' name='123' onClick={consultaApi}>Nova Iorque</Button>
                </TabPanel>
                {/* Tokyo */}
                <TabPanel> 
                  <p>three!</p>
                </TabPanel>
                {/* Cairo */}
                <TabPanel> 
                  <p>three!</p>
                </TabPanel>
                {/* Camberra */}
                <TabPanel> 
                  <p>three!</p>
                </TabPanel>
              </TabPanels>
            </Tabs>
          </Flex> 
      </main>
    </Flex>
  )
}

export default Home