import { FormEvent, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Flex, Box, Text, Input, Button, Image, Tabs, TabList, TabPanels, Tab, TabPanel } from '@chakra-ui/react';



const Home: NextPage = () => {
  const [texto, setTexto] = useState('');

  async function onSubmit(event: FormEvent){
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex align='center' justify-content= 'center'>
          <Box  w='100vw' h='1000vh' justify-content= 'center' bgImage="ceu.jpg" bgRepeat="no-repeat"> 
                <Tabs  align='center' variant='soft-rounded' colorScheme='green' >
                  <TabList>
                  <Tab>Londres</Tab>
                  <Tab>New York</Tab>
                  <Tab>Brasilia</Tab>
                  <Tab>Tokyo</Tab>
                  <Tab>Cairo</Tab>
                  <Tab>Camberra</Tab>
                </TabList>
                <TabPanels>
                {/* Londres */}
                <TabPanel> 
                  <p>TEMPERATURA E n sei!</p>
                </TabPanel>
                {/* New York */}
                <TabPanel> 
                  <p>two!</p>
                </TabPanel>
                {/* Brasilia */}
                <TabPanel> 
                  <p>three!</p>
                </TabPanel>
                {/* Tokyo */}
                <TabPanel> 
                  <p>three!</p>
                </TabPanel>
                {/* Cairo */}
                <TabPanel> 
                  <p>three!</p>
                </TabPanel>
                {/* Camberra */}
                <TabPanel> 
                  <p>three!</p>
                </TabPanel>
              </TabPanels>
            </Tabs>
          </Box>  
        </Flex>

      </main>
    </div>
  )
}

export default Home